name: CI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  XCODE_PROJECT: VoiceAssistant.xcodeproj
  XCODE_SCHEME: VoiceAssistant
jobs:
  build-and-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        include:
            # For information about the runner images and the software each image contains,
            # refer to: https://github.com/actions/runner-images
            - os: macos-15
              xcode: 16.2
              sdk: xrsimulator2.2
            - os: macos-15
              xcode: 16.2
              sdk: macosx15.2
            - os: macos-15
              xcode: 16.2
              sdk: iphonesimulator18.2
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ## Currently there are no tests that require the server to be running
      ## Uncomment this when adding tests that require the server to be running
      ## ------------------------------------------------------------------------
      # - name: Install LiveKit Server
      #  run: brew install livekit
      # - name: Run LiveKit Server
      #  run: livekit-server --dev &

      - name: Setup Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Print Versions
        run: |
          xcodebuild -version
          xcrun swift --version

      - name: Cache
        uses: irgaly/xcode-cache@v1
        with:
          key: xcode-${{ matrix.xcode }}-${{ matrix.sdk }}-${{ github.sha }}
          restore-keys: xcode-${{ matrix.xcode }}-${{ matrix.sdk }}-

      - name: Write Default Config
        run: cd VoiceAssistant && cat .env.example.xcconfig > .env.xcconfig

      - name: Build for Testing
        run: |
          set -o pipefail && xcodebuild build-for-testing \
            -project ${{ env.XCODE_PROJECT }} \
            -scheme ${{ env.XCODE_SCHEME }} \
            -sdk ${{ matrix.sdk }} \
            CODE_SIGN_IDENTITY="" | xcbeautify --renderer github-actions

      ## This project does not currently have tests
      ## Uncomment this once they are added
      ## ------------------------------------------------------------------------
      # - name: Run Tests
      #  run: |
      #    set -o pipefail && xcodebuild test-without-building \
      #      -project ${{ env.XCODE_PROJECT }} \
      #      -scheme ${{ env.XCODE_SCHEME }} \
      #      --sdk ${{ matrix.sdk }} \
      #      -parallel-testing-enabled YES \
      #      -parallel-testing-worker-count 4 | xcbeautify --renderer github-actions

  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat Lint
        run: swiftformat --lint . --reporter github-actions-log
        # Comes pre-installed on macOS runners
